server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # SPA yonlendirmesi: Bulunamayan her path index.html'e duser.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
