services:

  postgres:
    image: postgres:16-alpine
    container_name: apptivity-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: apptivity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d apptivity" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: apptivity-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/apptivity
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-1234}
      APP_JWT_SECRET: ${JWT_SECRET:-CHANGE_ME_USE_A_STRONG_256_BIT_SECRET_KEY_HERE}
      APP_JWT_EXPIRATION_MS: 86400000
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: apptivity-web
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      # Eğer ileride proxy kullanmazsanız veya build anında environment variable geçmek isterseniz burada tanımlayabilirsiniz.
      VITE_API_URL: http://localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data:
